language: python
python:
  - "2.7"
  - "3.4"
env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10

install:
    - pip install -r requirements/test.txt
    - pip install Django==$DJANGO
    - pip install .
script:
#  - cd listable-demo && python manage.py syncdb --noinput && cd ..
  - python runtests.py


sudo: false
