language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6

install:
    - pip install -r requirements/test.txt
    - pip install Django==$DJANGO
    - pip install .
script:
  - python runtests.py

matrix:
    exclude:
        - python: "3.4"
          env: DJANGO=1.4

sudo: false
