language: python
python:
  - "2.6"
  - "2.7"
env:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6

install:
    - pip install -q -e -r requirements-travis.txt
    - pip install -q -e Django==$DJANGO
script:
  - python runtests.py
