language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8

install:
    - pip install -r requirements/test.txt
    - pip install Django==$DJANGO
    - pip install .
script:
#  - cd listable-demo && python manage.py syncdb --noinput && cd ..
  - python runtests.py

matrix:
    exclude:
        - python: "3.4"
          env: DJANGO=1.4
        - python: "2.6"
          env: DJANGO=1.7
        - python: "2.6"
          env: DJANGO=1.8


sudo: false
